### ISSUE TITLE
pprint(qnap.get_smart_disk_health()) error on TS-110

### ISSUE THREAD

**Issue by alsa81** [colinodell/python-qnapstats#11]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: <TS-110>

**QTS Version**: <4.2.4>

If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**

~~~
FILE test.py:
#!/usr/bin/env python3
from qnapstats import QNAPStats
from pprint import pprint
qnap = QNAPStats('192.168.0.7', 8080, 'xxxx', 'xxxx')
# pprint(qnap.get_system_stats())
# pprint(qnap.get_system_health())
pprint(qnap.get_smart_disk_health())
# pprint(qnap.get_volumes())
# pprint(qnap.get_bandwidth())

ERROR:
(homeassistant) homeassistant@hassbian:/home/pi $ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    pprint(qnap.get_smart_disk_health())
  File "/srv/homeassistant/lib/python3.4/site-packages/qnapstats/qnap_stats.py", line 186, in get_smart_disk_health
    if disk["Model"]:
TypeError: string indices must be integers

~~~

**Comment by colinodell** [comment]
Thanks for reporting this issue!

Would you mind re-running your `test.py` script, but with debug mode enabled like this?

```python
qnap = QNAPStats('192.168.0.7', 8080, 'xxxx', 'xxxx', debugmode=True)
# Add this parameter ---------------------------------^^^^^^^^^^^^^^
```

That should provide the raw XML from your device which should help me pinpoint the issue.  (Feel free to `xxxxx` out any private information that may appear)

**Comment by alsa81** [comment]
(homeassistant) homeassistant@hassbian:/home/pi $ python test.py
DEBUG: Creating new session
DEBUG: POST to URL: http://192.168.0.7:8080/cgi-bin/authLogin.cgi
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><SMBFW><![CDATA[0]]></SMBFW><authPassed><![CDATA[1]]></authPassed><authSid><![CDATA[wyspw2re]]></authSid><isAdmin><![CDATA[1]]></isAdmin><username><![CDATA[admin]]></username><groupname><![CDATA[administrators]]></groupname><ts><![CDATA[68040657]]></ts><fwNotice><![CDATA[0]]></fwNotice><SUID><![CDATA[c07e89d18edda33d77a507cd19a1a5dd]]></SUID><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><showVersion><![CDATA[0]]></showVersion><show_link><![CDATA[1]]></show_link></QDocRoot>

DEBUG: GET from URL: http://192.168.0.7:8080/cgi-bin/disk/qsmart.cgi?func=all_hd_data
DEBUG: Appending access_token (SID: wyspw2re) to url
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[1]]></authPassed><model><modelName><![CDATA[TS-110]]></modelName><internalModelName><![CDATA[TS-119]]></internalModelName><platform><![CDATA[TS-NASARM]]></platform><customModelName><![CDATA[]]></customModelName><displayModelName><![CDATA[TS-110]]></displayModelName><storage_v2>0</storage_v2>
</model>
<firmware><version><![CDATA[4.2.4]]></version><build><![CDATA[20170313]]></build><patch><![CDATA[0]]></patch><buildTime><![CDATA[2017/03/13]]></buildTime></firmware>
<specVersion><![CDATA[1.0]]></specVersion><hostname><![CDATA[KIWIQNAP]]></hostname><DemoSiteSuppurt><![CDATA[no]]></DemoSiteSuppurt><customLogo><customFrontLogo><![CDATA[]]></customFrontLogo><customLoginLogo><![CDATA[]]></customLoginLogo></customLogo>
<HDTempWarnT><![CDATA[55]]></HDTempWarnT><HDTempErrT><![CDATA[60]]></HDTempErrT><Disk_Info><entry><Disk_Status><![CDATA[0]]></Disk_Status><HDNo><![CDATA[1]]></HDNo><Vendor><![CDATA[WDC     WD30EFRX-68EUZN080.0]]></Vendor><io_health><![CDATA[OK]]></io_health><Health><![CDATA[OK]]></Health><Capacity><![CDATA[2.73 TB]]></Capacity><Temperature><oC><![CDATA[37]]></oC><oF><![CDATA[98]]></oF></Temperature>
<LastTestSts><![CDATA[]]></LastTestSts><LastTestType><![CDATA[]]></LastTestType><LastTestTime><![CDATA[]]></LastTestTime><Model><![CDATA[WDC WD30EFRX-68EUZN0]]></Model><Serial><![CDATA[WD-WCC4N0795818]]></Serial><FirmVersion><![CDATA[80.00A80]]></FirmVersion><ATAVersion><![CDATA[ATA-9 ]]></ATAVersion><ATADescription><![CDATA[Exact ATA specification draft version not indicated]]></ATADescription></entry>
</Disk_Info>
</QDocRoot>

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    pprint(qnap.get_smart_disk_health())
  File "/srv/homeassistant/lib/python3.4/site-packages/qnapstats/qnap_stats.py", line 186, in get_smart_disk_health
    if disk["Model"]:
TypeError: string indices must be integers

**Comment by colinodell** [comment]
Hmm it looks like your device may not support smart disk health.  (Or perhaps QNAP changed the URL for this in 4.2.4 - I'll update my device to check this)

**Comment by alsa81** [comment]
Thanks for your support; qnapstats library is used by "home-assistant" project and i'm a final user, not a developer. Sorry if my informations are not so clear.

**Comment by alsa81** [comment]
Same as yesterday, but with XML syntax enabled (Thanks to [http://stackoverflow.com/questions/16434836/how-to-post-raw-xml-in-github-comment](url))
```xml
(homeassistant) homeassistant@hassbian:/home/pi $ python test.py
DEBUG: Creating new session
DEBUG: POST to URL: http://192.168.0.7:8080/cgi-bin/authLogin.cgi
DEBUG: Request executed: 200
DEBUG: Response Text: 
<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><SMBFW><![CDATA[0]]></SMBFW><authPassed><![CDATA[1]]></authPassed><authSid><![CDATA[3hj2h6fm]]></authSid><isAdmin><![CDATA[1]]></isAdmin><username><![CDATA[admin]]></username><groupname><![CDATA[administrators]]></groupname><ts><![CDATA[68040657]]></ts><fwNotice><![CDATA[0]]></fwNotice><SUID><![CDATA[c07e89d18edda33d77a507cd19a1a5dd]]></SUID><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><showVersion><![CDATA[0]]></showVersion><show_link><![CDATA[1]]></show_link></QDocRoot>

DEBUG: GET from URL: http://192.168.0.7:8080/cgi-bin/disk/qsmart.cgi?func=all_hd_data
DEBUG: Appending access_token (SID: 3hj2h6fm) to url
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[1]]></authPassed><model><modelName><![CDATA[TS-110]]></modelName><internalModelName><![CDATA[TS-119]]></internalModelName><platform><![CDATA[TS-NASARM]]></platform><customModelName><![CDATA[]]></customModelName><displayModelName><![CDATA[TS-110]]></displayModelName><storage_v2>0</storage_v2>
</model>
<firmware><version><![CDATA[4.2.4]]></version><build><![CDATA[20170313]]></build><patch><![CDATA[0]]></patch><buildTime><![CDATA[2017/03/13]]></buildTime></firmware>
<specVersion><![CDATA[1.0]]></specVersion><hostname><![CDATA[KIWIQNAP]]></hostname><DemoSiteSuppurt><![CDATA[no]]></DemoSiteSuppurt><customLogo><customFrontLogo><![CDATA[]]></customFrontLogo><customLoginLogo><![CDATA[]]></customLoginLogo></customLogo>
<HDTempWarnT><![CDATA[55]]></HDTempWarnT><HDTempErrT><![CDATA[60]]></HDTempErrT><Disk_Info><entry><Disk_Status><![CDATA[0]]></Disk_Status><HDNo><![CDATA[1]]></HDNo><Vendor><![CDATA[WDC     WD30EFRX-68EUZN080.0]]></Vendor><io_health><![CDATA[OK]]></io_health><Health><![CDATA[OK]]></Health><Capacity><![CDATA[2.73 TB]]></Capacity><Temperature><oC><![CDATA[37]]></oC><oF><![CDATA[98]]></oF></Temperature>
<LastTestSts><![CDATA[]]></LastTestSts><LastTestType><![CDATA[]]></LastTestType><LastTestTime><![CDATA[]]></LastTestTime><Model><![CDATA[WDC WD30EFRX-68EUZN0]]></Model><Serial><![CDATA[WD-WCC4N0795818]]></Serial><FirmVersion><![CDATA[80.00A80]]></FirmVersion><ATAVersion><![CDATA[ATA-9 ]]></ATAVersion><ATADescription><![CDATA[Exact ATA specification draft version not indicated]]></ATADescription></entry>
</Disk_Info>
</QDocRoot>

Traceback (most recent call last):
  File "test.py", line 9, in <module>
    pprint(qnap.get_smart_disk_health())
  File "/srv/homeassistant/lib/python3.4/site-packages/qnapstats/qnap_stats.py", line 186, in get_smart_disk_health
    if disk["Model"]:
TypeError: string indices must be integers
(homeassistant) homeassistant@hassbian:/home/pi $

**Comment by colinodell** [comment]
Thanks so much for providing that XML!  I've resolved the issue.  I'll get a new version of this package released ASAP and will also submit a PR for Home Assistant.

**Comment by colinodell** [comment]
Update released; PR for HASS is pending: https://github.com/home-assistant/home-assistant/pull/7084

Thanks again for your help!
