### ISSUE TITLE
Install Error 

### ISSUE THREAD

**Issue by Madseason41** [colinodell/python-qnapstats#13]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: <TS-219 PII>

**QTS Version**: <4.3.3>

I experience the following issue on install...

any ideas as to why?

Collecting qnapstats
  Downloading qnapstats-0.2.4.tar.gz
    Complete output from command python setup.py egg_info:
    /opt/lib/python3.6/distutils/dist.py:261: UserWarning: Unknown distribution option: 'install_requires'
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help
    
    error: invalid command 'egg_info'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /share/MD0_DATA/.qpkg/Entware-3x/tmp/pip-build-7boku_iy/qnapstats/
If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**

~~~
<Insert your XML or debug output here>
~~~

**Comment by colinodell** [comment]
Unfortunately this error is beyond my Python skills to figure out :-/  Although this library is intended for use outside of the QNAP, there's no reason it shouldn't work on the QNAP itself.  I'll leave this open in case others have similar issues and find a solution which may help you.

**Comment by Madseason41** [comment]
solved by "pip3 install --upgrade setuptools".  Please close.

**Comment by colinodell** [comment]
Awesome, I'm glad you were able to figure it out!
