### ISSUE TITLE
Remote unlock of encrypted volumes

### ISSUE THREAD

**Issue by SeeSpotRun** [colinodell/python-qnapstats#14]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: TS-228

**QTS Version**: 4.3.4

I was looking to leverage off your fine library to build a remote unlocker script for encrypted volumes.  I can't find any good documentation for the API but I'm beginning to suspect it doesn't include unlocking encrypted volumes... any ideas where else I should look?

**Comment by colinodell** [comment]
Thanks for submitting this!  Unfortunately unlocking encrypted volumes is outside my personal expertise and what I'd like this library to focus on :-/  But maybe this will help:

The API I'm using for fetching stats wasn't documented either.  Essentially what I did was open the web interface, fire up Chrome's dev tools, and watched the network requests going back and forth.  I was able to determine which URLs/calls provided the system stats and then simply implemented similar HTTP calls here.  If there's a way to unlock volumes via the web interface then you might be able to use the same approach of monitoring HTTP requests to figure out the API.

I hope that helps - best of luck!

**Comment by SeeSpotRun** [comment]
Thanks for the tip; I'll see how I go (first time debugging cgi, and the QNAP code is obfuscated).  The URL seems to be `...cgi-bin/disk/disk_manage.cgi` but I need to figure out how to pass the parameters to it:
```
func:"open_encrypt_dev"
keyStr:"my_secret_pwd"
saveKey:"no"
volumeID:"1"
```
