### ISSUE TITLE
dependency error

### ISSUE THREAD

**Issue by brunohorta82** [colinodell/python-qnapstats#18]
pip3 install xmltodict>=0.10.0
python-jose-cryptodome 1.3.2 has requirement pycryptodome<3.4.0,>=3.3.1, but you'll have pycryptodome 3.4.11 which is incompatible.
pyatv 0.3.9 has requirement aiohttp<3,>=2.3.0, but you'll have aiohttp 3.1.1 which is incompatible.
netdisco 1.2.3 has requirement zeroconf==0.19.1, but you'll have zeroconf 0.20.0 which is incompatible.

**Comment by colinodell** [comment]
It sounds like you might have some mismatched dependencies on your system.  I just tried running `pip3 install xmltodict>=0.10.0` on my main machine as well as a fresh installation of Linux and it worked fine on both.

I'm not an expert on pip though, so unfortunately I can't provide too much guidance on how to correct that.  I'd recommend asking for support on StackOverflow/ServerFault - hopefully someone with more experience can help you resolve this.
