### ISSUE TITLE
Works with TS-453A

### ISSUE THREAD

**Issue by benjgos** [colinodell/python-qnapstats#20]
Just an FYI - 
Works great with my TS-453A running FW 4.3.4.
I would add to the docs that this requires the user be in the admin group.
At least I couldn't limit it. If you have some ideas on how to do it, please share. :)
Except for that, This is super useful! I'm using it in Home Assistant.

**Comment by colinodell** [comment]
Thanks for sharing that!  I have updated the README accordingly.  :beers:
