### ISSUE TITLE
TS-269L Compatibility

### ISSUE THREAD

**Issue by ErikKnowles** [colinodell/python-qnapstats#27]
You might want to add the TS-269L, firmware 4.3.3 to your compatibility list. The library's working just fine for me.

Oh, also: I'm using qnap_stats out of the box with python 2.7. There appears to be no compatibility issues.

**Comment by colinodell** [comment]
Thanks for letting me know about both the device and Python 2.7 compatibility!

I've added the former one to the list in our README.

If you (or someone else) would like to open a PR to "officially" add Python 2.7 support I'd be happy to merge it!  IMO this should include:

 - **Updating `.travis.yml` and `tox.ini` to run the tests on 2.7, ensuring they all pass**
 - Adding 2.7 to `setup.py`
 - Whatever else might need to be done

I'm not an experienced Python developer, definitely not enough to fully understand the differences between 2.x and 3.x or best practices around supporting both versions simultaneously, so any help would be appreciated!
