### ISSUE TITLE
TS-431 Confirmed working

### ISSUE THREAD

**Issue by The-May** [colinodell/python-qnapstats#33]
It seems to work on my:
**Device Model Number**: TS-431
**QTS Version**: 4.3.4.0569 Build 20180501

![qnas](https://user-images.githubusercontent.com/47433911/71557737-88d79e00-2a4a-11ea-8b84-cf9eb4498bff.png)

Thank you and keep up the awesome work.

**Comment by colinodell** [comment]
Thanks for the confirmation! I've [updated the README](https://github.com/colinodell/python-qnapstats/commit/8fbb87b99580629c0e0e81358ea888d84301b317) accordingly :)
