### ISSUE TITLE
External drive info

### ISSUE THREAD

**Issue by PavelD** [colinodell/python-qnapstats#34]
I'm using us external drives and it will be great to see the status in my home assistant dashboard.

The basic info is available from the menu bar and later in the Storage & Snapshots app under External Storage menu.

![image](https://user-images.githubusercontent.com/447416/71729280-8fe22000-2e3f-11ea-94be-020b9129cec2.png) 
Storage information are following:
* Label
* Manufacturer
* File System
* Device Type
* Total / Free Size
* Shared Folder

![image](https://user-images.githubusercontent.com/447416/71730568-cec5a500-2e42-11ea-9e2d-5b4ec5fd53e2.png)

Is it possible to propagate at least some information to the home assistant sensor? 

To have at least label, volume_size_free and volume_size_used will be great.

Thanks a lot for all you effort.

**Comment by colinodell** [comment]
Yeah, it should technically be possible to do this.  Basically, somebody will need to use Chrome's Developer Tools to figure out the HTTP request that the QNAP web interface makes to retrieve this information.  Once we know the URL to call, which parameters (if any) to pass it, and what the output is, it should be possible to replicate those HTTP calls in this library so we can expose that information to HA.

Is this something you'd feel comfortable doing?  If not, we'll just need somebody else with a similar setup and the technical know-how to help us reverse engineer those HTTP requests.

**Comment by PavelD** [comment]
Hi, yes. I was trying to do it in Firefox Developer toolbar but got had bunch of request at the same time and i was not able to reach the correct call.

I will try to dump communication and grep the correct values.

**Comment by PavelD** [comment]
OK, so burp helped me :-) Here you have it:

POST `func=getExternalDev` to https://MY_IP/cgi-bin/devices/devRequest.cgi?sid=XXX 

`<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
    <authPassed>
        <![CDATA[1]]]>
        <![CDATA[]>
    </authPassed>
    <model>
        <modelName>
            <![CDATA[TS-X41]]]>
            <![CDATA[]>
        </modelName>
        <internalModelName>
            <![CDATA[TS-X41]]]>
            <![CDATA[]>
        </internalModelName>
        <platform>
            <![CDATA[TS-NASARM]]]>
            <![CDATA[]>
        </platform>
        <platform_ex>
            <![CDATA[ARM_AL]]]>
            <![CDATA[]>
        </platform_ex>
        <customModelName>
            <![CDATA[]]]>
            <![CDATA[]>
        </customModelName>
        <displayModelName>
            <![CDATA[TS-231+]]]>
            <![CDATA[]>
        </displayModelName>
        <sas_model>
            <![CDATA[0]]]>
            <![CDATA[]>
        </sas_model>
        <storage_v2>1</storage_v2>
        <encryptfsSupported>
            <![CDATA[1]]]>
            <![CDATA[]>
        </encryptfsSupported>
    </model>
    <firmware>
        <version>
            <![CDATA[4.4.1]]]>
            <![CDATA[]>
        </version>
        <number>
            <![CDATA[1146]]]>
            <![CDATA[]>
        </number>
        <build>
            <![CDATA[20191206]]]>
            <![CDATA[]>
        </build>
        <patch>
            <![CDATA[0]]]>
            <![CDATA[]>
        </patch>
        <buildTime>
            <![CDATA[2019/12/06]]]>
            <![CDATA[]>
        </buildTime>
    </firmware>
    <rfs_bits>
        <![CDATA[32]]]>
        <![CDATA[]>
    </rfs_bits>
    <specVersion>
        <![CDATA[1.0]]]>
        <![CDATA[]>
    </specVersion>
    <hostname>
        <![CDATA[XXX]]]>
        <![CDATA[]>
    </hostname>
    <DemoSiteSuppurt>
        <![CDATA[no]]]>
        <![CDATA[]>
    </DemoSiteSuppurt>
    <customLogo>
        <customFrontLogo>
            <![CDATA[]]]>
            <![CDATA[]>
        </customFrontLogo>
        <customLoginLogo>
            <![CDATA[]]]>
            <![CDATA[]>
        </customLoginLogo>
    </customLogo>
    <action>
        <![CDATA[none]]]>
        <![CDATA[]>
    </action>
    <func>
        <name>
            <![CDATA[MENU_8]]]>
            <![CDATA[]>
        </name>
        <ownContent>
            <externalDevice>
                <HAL>
                    <![CDATA[1]]]>
                    <![CDATA[]>
                </HAL>
                <SupportEXT4>Y</SupportEXT4>
                <SupportHFSPLUS>Y</SupportHFSPLUS>
                <Disk_Num>2</Disk_Num>
                <Disk_Vol>
                    <Device_ID>1</Device_ID>
                    <Device_Type>0</Device_Type>
                    <Disk_List>IcyBox</Disk_List>
                    <permission>W</permission>
                    <only_admin>0</only_admin>
                    <Disk_Selected>2</Disk_Selected>
                    <Disk_Path>/dev/sdc</Disk_Path>
                    <Disk_Manufacture>JMB352</Disk_Manufacture>
                    <Disk_Model>RAID-1</Disk_Model>
                    <Disk_Type>USB 3.0</Disk_Type>
                    <Disk_Size_Info>1.81 TB / 387.47 GB</Disk_Size_Info>
                    <Disk_File_System>EXT4</Disk_File_System>
                    <Disk_Status>IEI_DEVICE_MSG31</Disk_Status>
                    <Disk_Format_Progress>(100%)</Disk_Format_Progress>
                    <DISK_STOPPING>0</DISK_STOPPING>
                    <isEncrypted>0</isEncrypted>
                    <Disk_Is_ODD>0</Disk_Is_ODD>
                    <Disk_Is_MTP>0</Disk_Is_MTP>
                </Disk_Vol>
                <Disk_Vol>
                    <Device_ID>2</Device_ID>
                    <Device_Type>0</Device_Type>
                    <Disk_List>USBDisk2</Disk_List>
                    <permission>W</permission>
                    <only_admin>0</only_admin>
                    <Disk_Selected>3</Disk_Selected>
                    <Disk_Path>/dev/sdd</Disk_Path>
                    <Disk_Manufacture>OEM</Disk_Manufacture>
                    <Disk_Model>Ext Hard Disk</Disk_Model>
                    <Disk_Type>USB 3.0</Disk_Type>
                    <Disk_Size_Info>3.40 TB / 880.60 GB</Disk_Size_Info>
                    <Disk_File_System>EXT4</Disk_File_System>
                    <Disk_Status>IEI_DEVICE_MSG31</Disk_Status>
                    <Disk_Format_Progress>(100%)</Disk_Format_Progress>
                    <DISK_STOPPING>0</DISK_STOPPING>
                    <isEncrypted>0</isEncrypted>
                    <Disk_Is_ODD>0</Disk_Is_ODD>
                    <Disk_Is_MTP>0</Disk_Is_MTP>
                </Disk_Vol>
            </externalDevice>
        </ownContent>
    </func>
</QDocRoot>`

Is it enough? (Sorry, I don't know how to nicely paste XML content...)

**Comment by PavelD** [comment]
Second request is:

POST /cgi-bin/disk/disk_manage.cgi?sid=XXX&store=external_get_all to https://MY_IP/cgi-bin/disk/disk_manage.cgi?sid=XXX&store=external_get_all

Response is:

`<?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
    <authPassed>
        <![CDATA[1]]]>
        <![CDATA[]>
    </authPassed>
    <model>
        <modelName>
            <![CDATA[TS-X41]]]>
            <![CDATA[]>
        </modelName>
        <internalModelName>
            <![CDATA[TS-X41]]]>
            <![CDATA[]>
        </internalModelName>
        <platform>
            <![CDATA[TS-NASARM]]]>
            <![CDATA[]>
        </platform>
        <platform_ex>
            <![CDATA[ARM_AL]]]>
            <![CDATA[]>
        </platform_ex>
        <customModelName>
            <![CDATA[]]]>
            <![CDATA[]>
        </customModelName>
        <displayModelName>
            <![CDATA[TS-231+]]]>
            <![CDATA[]>
        </displayModelName>
        <sas_model>
            <![CDATA[0]]]>
            <![CDATA[]>
        </sas_model>
        <storage_v2>1</storage_v2>
        <encryptfsSupported>
            <![CDATA[1]]]>
            <![CDATA[]>
        </encryptfsSupported>
    </model>
    <firmware>
        <version>
            <![CDATA[4.4.1]]]>
            <![CDATA[]>
        </version>
        <number>
            <![CDATA[1146]]]>
            <![CDATA[]>
        </number>
        <build>
            <![CDATA[20191206]]]>
            <![CDATA[]>
        </build>
        <patch>
            <![CDATA[0]]]>
            <![CDATA[]>
        </patch>
        <buildTime>
            <![CDATA[2019/12/06]]]>
            <![CDATA[]>
        </buildTime>
    </firmware>
    <rfs_bits>
        <![CDATA[32]]]>
        <![CDATA[]>
    </rfs_bits>
    <specVersion>
        <![CDATA[1.0]]]>
        <![CDATA[]>
    </specVersion>
    <hostname>
        <![CDATA[XXX]]]>
        <![CDATA[]>
    </hostname>
    <DemoSiteSuppurt>
        <![CDATA[no]]]>
        <![CDATA[]>
    </DemoSiteSuppurt>
    <customLogo>
        <customFrontLogo>
            <![CDATA[]]]>
            <![CDATA[]>
        </customFrontLogo>
        <customLoginLogo>
            <![CDATA[]]]>
            <![CDATA[]>
        </customLoginLogo>
    </customLogo>
    <DiskManageModel>Version1.01</DiskManageModel>
    <SupportEXT4>Y</SupportEXT4>
    <SupportHFSPLUS>Y</SupportHFSPLUS>
    <SupportEXFAT>Y</SupportEXFAT>
    <EnabledEXFAT>N</EnabledEXFAT>
    <Disk_Num>2</Disk_Num>
    <Disk_Vol>
        <Device_ID>1</Device_ID>
        <Part_No>1</Part_No>
        <enclosureID>33</enclosureID>
        <Device_Type>0</Device_Type>
        <Disk_List>2:USBDisk1</Disk_List>
        <Disk_Selected>2</Disk_Selected>
        <Vol_Label>IcyBox</Vol_Label>
        <Share_Folder>IcyBox</Share_Folder>
        <Disk_Path>/dev/sdc</Disk_Path>
        <Disk_Manufacture>JMB352</Disk_Manufacture>
        <Disk_Model>RAID-1</Disk_Model>
        <Disk_Type>USB 3.0</Disk_Type>
        <Disk_Size_Info>1.81 TB / 387.47 GB</Disk_Size_Info>
        <Disk_File_System>EXT4</Disk_File_System>
        <Disk_Status>IEI_DEVICE_MSG31</Disk_Status>
        <Disk_Format_Progress>(100%)</Disk_Format_Progress>
        <DISK_STOPPING>0</DISK_STOPPING>
        <Disk_Is_ODD>0</Disk_Is_ODD>
        <used_size>1.43 TB</used_size>
        <total_size>1.82 TB</total_size>
        <isEncrypted>0</isEncrypted>
        <Disk_Is_MTP>0</Disk_Is_MTP>
    </Disk_Vol>
    <Disk_Vol>
        <Device_ID>2</Device_ID>
        <Part_No>1</Part_No>
        <enclosureID>33</enclosureID>
        <Device_Type>0</Device_Type>
        <Disk_List>3:USBDisk2</Disk_List>
        <Disk_Selected>3</Disk_Selected>
        <Vol_Label>USBDisk2</Vol_Label>
        <Share_Folder>USBDisk2</Share_Folder>
        <Disk_Path>/dev/sdd</Disk_Path>
        <Disk_Manufacture>OEM</Disk_Manufacture>
        <Disk_Model>Ext Hard Disk</Disk_Model>
        <Disk_Type>USB 3.0</Disk_Type>
        <Disk_Size_Info>3.40 TB / 880.60 GB</Disk_Size_Info>
        <Disk_File_System>EXT4</Disk_File_System>
        <Disk_Status>IEI_DEVICE_MSG31</Disk_Status>
        <Disk_Format_Progress>(100%)</Disk_Format_Progress>
        <DISK_STOPPING>0</DISK_STOPPING>
        <Disk_Is_ODD>0</Disk_Is_ODD>
        <used_size>2.54 TB</used_size>
        <total_size>3.64 TB</total_size>
        <isEncrypted>0</isEncrypted>
        <Disk_Is_MTP>0</Disk_Is_MTP>
    </Disk_Vol>
    <result>0</result>
</QDocRoot>`

**Comment by carsten-h** [comment]
It would be really great to have those values in Home Assistant!
I want to detect if an external drive is mounted or not with this information.

**Comment by carsten-h** [comment]
Is there any chance that this will be implemented?

**Comment by carsten-h** [comment]
Is there really no one who can help here?

**Comment by PavelD** [comment]
I moved all external USB drives out of the NAS (after i lost some data) so I'm not able to reproduce it any more.

But I still think it will be great to have it in the integration. Workaround is to use shell_command sensor and ssh to nas machine and collect info from mount and df commands.

**Comment by carsten-h** [comment]
It seems no one is really caring about this software?

**Comment by julien-bouquet** [comment]
Hello, 

I will try to work on it this week

**Comment by carsten-h** [comment]
> this week

When will this be included in a release?
