### ISSUE TITLE
TS-431P Compatibility

### ISSUE THREAD

**Issue by ghost** [colinodell/python-qnapstats#37]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: TS-431P

**QTS Version**: <4.4.2>

If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**

~~~
No Output
~~~

**Comment by cdn77-blackfire** [comment]
If i run on my QNAP TS-431 your example code i got just 5x None.
with runing debug and connecting to http port of my NAS i have this output:

`root@blackbox:~# ./debug.py 
Host (prefix with 'https://' if needed): 192.168.0.11
Port: 1180
Username: roman
Password: 
DEBUG: Creating new session
DEBUG: POST to URL: http://192.168.0.11:1180/cgi-bin/authLogin.cgi
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><shutdown_info><type><![CDATA[-1]]></type><timestamp><![CDATA[0]]></timestamp><duration><![CDATA[0]]></duration></shutdown_info>
<SMBFW><![CDATA[0]]></SMBFW><hero_model><![CDATA[0]]></hero_model><qts_mode_type><![CDATA[0]]></qts_mode_type><authPassed><![CDATA[1]]></authPassed><authSid><![CDATA[30u8dolb]]></authSid><isAdmin><![CDATA[0]]></isAdmin><userid><![CDATA[500]]></userid><userType><![CDATA[local]]></userType><user_pw_change><![CDATA[1]]></user_pw_change><username><![CDATA[roman]]></username><groupname><![CDATA[everyone]]></groupname><ts><![CDATA[24091563]]></ts><fwNotice><![CDATA[0]]></fwNotice><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><standard_massage><![CDATA[]]></standard_massage><standard_color><![CDATA[#ffffff]]></standard_color><standard_size><![CDATA[12px]]></standard_size><standard_bg_style><![CDATA[fill]]></standard_bg_style><showVersion><![CDATA[0]]></showVersion><show_link><![CDATA[1]]></show_link><cuid><![CDATA[c5f4ed6b02beecb44df3a61215faea0b]]></cuid></QDocRoot>

DEBUG: GET from URL: http://192.168.0.11:1180/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1
DEBUG: Appending access_token (SID: 30u8dolb) to url
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[0]]></authPassed></QDocRoot>

DEBUG: Error occured, retrying...
DEBUG: Creating new session
DEBUG: POST to URL: http://192.168.0.11:1180/cgi-bin/authLogin.cgi
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><shutdown_info><type><![CDATA[-1]]></type><timestamp><![CDATA[0]]></timestamp><duration><![CDATA[0]]></duration></shutdown_info>
<SMBFW><![CDATA[0]]></SMBFW><hero_model><![CDATA[0]]></hero_model><qts_mode_type><![CDATA[0]]></qts_mode_type><authPassed><![CDATA[1]]></authPassed><authSid><![CDATA[4rol9pp7]]></authSid><isAdmin><![CDATA[0]]></isAdmin><userid><![CDATA[500]]></userid><userType><![CDATA[local]]></userType><user_pw_change><![CDATA[1]]></user_pw_change><username><![CDATA[roman]]></username><groupname><![CDATA[everyone]]></groupname><ts><![CDATA[24091563]]></ts><fwNotice><![CDATA[0]]></fwNotice><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><standard_massage><![CDATA[]]></standard_massage><standard_color><![CDATA[#ffffff]]></standard_color><standard_size><![CDATA[12px]]></standard_size><standard_bg_style><![CDATA[fill]]></standard_bg_style><showVersion><![CDATA[0]]></showVersion><show_link><![CDATA[1]]></show_link><cuid><![CDATA[c5f4ed6b02beecb44df3a61215faea0b]]></cuid></QDocRoot>

`

**Comment by colinodell** [comment]
Thanks for sharing that information!  This is really helpful.

In this case, it seems that either the TS-431 doesn't support using access tokens to fetch data like other models do, or it simply doesn't provide data at those URLs.  In either case, there's unfortunately not much I can do, as supporting this device would require somebody to reverse-engineer the AJAX calls that it uses to fetch data for the admin interface.  If you or somebody else is up for that challenge, please feel free to send along your findings on how authenticated requests work or where to pull the data from.  (Or better yet - submit a pull request with working support! :wink:)

**Comment by cerberek** [comment]
If i run try get stats from my QNAP TS-431 with current version 4.5.1.1480 i got from your example code just 5x None.
with runing debug and connecting to http port of my NAS i have this output:
```
Host (prefix with 'https://' if needed): 192.168.0.11
Port: 1180
Username: roman
Password: 
DEBUG: Creating new session
DEBUG: POST to URL: http://192.168.0.11:1180/cgi-bin/authLogin.cgi
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><shutdown_info><type><![CDATA[-1]]></type><timestamp><![CDATA[0]]></timestamp><duration><![CDATA[0]]></duration></shutdown_info>
<SMBFW><![CDATA[0]]></SMBFW><hero_model><![CDATA[0]]></hero_model><qts_mode_type><![CDATA[0]]></qts_mode_type><authPassed><![CDATA[1]]></authPassed><authSid><![CDATA[30u8dolb]]></authSid><isAdmin><![CDATA[0]]></isAdmin><userid><![CDATA[500]]></userid><userType><![CDATA[local]]></userType><user_pw_change><![CDATA[1]]></user_pw_change><username><![CDATA[roman]]></username><groupname><![CDATA[everyone]]></groupname><ts><![CDATA[24091563]]></ts><fwNotice><![CDATA[0]]></fwNotice><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><standard_massage><![CDATA[]]></standard_massage><standard_color><![CDATA[#ffffff]]></standard_color><standard_size><![CDATA[12px]]></standard_size><standard_bg_style><![CDATA[fill]]></standard_bg_style><showVersion><![CDATA[0]]></showVersion><show_link><![CDATA[1]]></show_link><cuid><![CDATA[c5f4ed6b02beecb44df3a61215faea0b]]></cuid></QDocRoot>

DEBUG: GET from URL: http://192.168.0.11:1180/cgi-bin/management/manaRequest.cgi?subfunc=sysinfo&hd=no&multicpu=1
DEBUG: Appending access_token (SID: 30u8dolb) to url
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<authPassed><![CDATA[0]]></authPassed></QDocRoot>

DEBUG: Error occured, retrying...
DEBUG: Creating new session
DEBUG: POST to URL: http://192.168.0.11:1180/cgi-bin/authLogin.cgi
DEBUG: Request executed: 200
DEBUG: Response Text: <?xml version="1.0" encoding="UTF-8" ?>
<QDocRoot version="1.0">
<doQuick><![CDATA[]]></doQuick><is_booting><![CDATA[0]]></is_booting><mediaReady><![CDATA[1]]></mediaReady><shutdown_info><type><![CDATA[-1]]></type><timestamp><![CDATA[0]]></timestamp><duration><![CDATA[0]]></duration></shutdown_info>
<SMBFW><![CDATA[0]]></SMBFW><hero_model><![CDATA[0]]></hero_model><qts_mode_type><![CDATA[0]]></qts_mode_type><authPassed><![CDATA[1]]></authPassed><authSid><![CDATA[4rol9pp7]]></authSid><isAdmin><![CDATA[0]]></isAdmin><userid><![CDATA[500]]></userid><userType><![CDATA[local]]></userType><user_pw_change><![CDATA[1]]></user_pw_change><username><![CDATA[roman]]></username><groupname><![CDATA[everyone]]></groupname><ts><![CDATA[24091563]]></ts><fwNotice><![CDATA[0]]></fwNotice><title><![CDATA[]]></title><content><![CDATA[]]></content><psType><![CDATA[1]]></psType><standard_massage><![CDATA[]]></standard_massage><standard_color><![CDATA[#ffffff]]></standard_color><standard_size><![CDATA[12px]]></standard_size><standard_bg_style><![CDATA[fill]]></standard_bg_style><showVersion><![CDATA[0]]></showVersion><show_link><![CDATA[1]]></show_link><cuid><![CDATA[c5f4ed6b02beecb44df3a61215faea0b]]></cuid></QDocRoot>``` I had to remove my last comment, but this is just copy paste
