### ISSUE TITLE
Device QNAP TS-453Be with firmware 4.4.2.1320 is compatible

### ISSUE THREAD

**Issue by freemann** [colinodell/python-qnapstats#38]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: < TS-453Be >

**QTS Version**: <4.2.3>

This device<>firmware combination is compatible with qnapstats.

**XML/Debug Output:**

~~~
<Insert your XML or debug output here>
~~~

**Comment by colinodell** [comment]
Thanks for that info! I've updated the list of compatible devices.
