### ISSUE TITLE
Question; What rights does a account need to get the information from the NAS?

### ISSUE THREAD

**Issue by freemann** [colinodell/python-qnapstats#40]
I previously was using, quick and dirty, the admin account for the HA sensor.
Now I created a new account without admin privileges and the sensor isn't working anymore.

I hope the sensor doesn't need the Administrator group/privileges?

If there another way to ask question, please let me known :)

**Comment by colinodell** [comment]
Based on some quick research a while back, [it does seem like QNAP only provides this data to admin users](https://github.com/colinodell/python-qnapstats/issues/19#issuecomment-403984791) :-/
