### ISSUE TITLE
New maintainer wanted

### ISSUE THREAD

**Issue by colinodell** [colinodell/python-qnapstats#43]
This project has reached the level of maturity for my personal needs, but judging by the 7 open issues there is still some interest in expanding compatibility and features further.  I unfortunately have competing priorities in my personal life that will prevent me from addressing most of those open issues.

**I am therefore looking for anyone who would be interested in taking over this project.**  You would receive full administrator access to this repository and have full authority to merge code, create releases, or anything else a project owner would normally do.  I can be around to answer simple questions but would no longer maintain this repository.

The ideal person to take over this repository would match the following:

 - You own a QNAP device
 - You use Home Assistant
 - You've successfully contributed to this project or to Home Assistant in the past
 - You know how to release libraries and new versions on PyPI (or know enough about the Python ecosystem to figure it out)

If you feel you meet those (or at least come very close), please let me know about your interest :)  Either reply below or [email me](https://github.com/colinodell/python-qnapstats/blob/master/setup.py#L15).

**Comment by julien-bouquet** [comment]
Hello, 

I a newbie on QNAP device, and Home Assistant, but I'm a python developper. 
I hava a QNAP NAS TS251+ and Home Assistant, 
In this case, i cannot connect my Home Assistant with my QNAP. I've open PR to fix it.  

So i can help you to maintains this repository if you want.

**Comment by colinodell** [comment]
Hey @julien-bouquet,

Thanks for the offer!  Would you feel comfortable being the primary maintainer?  If so, please let me know your pypi.org username and I'll give you full owner/admin rights both here in GitLab and on pypi.org.

**Comment by julien-bouquet** [comment]
Hello, 

Sorry for the delay,

I can try to help you in first time. It will be my first time in maintainer of open source repository. 
I'm python developer but, in my job we don't do open source and we don't publish on pypi.org. 
We have private artifactory.

**Comment by colinodell** [comment]
Thanks @julien-bouquet! I've invited you to become a collaborator so you can help maintain this moving forward.  Let me know your username on PyPi (create an account if you don't have one yet) and I'll add you there as well :)

For this next release, I'd be happy to document the process for you once I relearn how to do it myself! haha

**Comment by julien-bouquet** [comment]
My username on PyPi is `julien-bouquet`. 

Yes, I will happy to learn how do release.

**Comment by julien-bouquet** [comment]
Sorry for the delay, i was in holiday, and i didn't received notification on issue or pull request on this project. 
I activate it. And i will try to take more time for this project

**Comment by colinodell** [comment]
No problem, I completely understand :)

I implemented a few things to simplify project maintenance:

 - Migrated automated tests to GitHub actions
 - Implemented an automated release process: just bump the version number in `setup.py`, publish a release on GitHub, and the package will push to PyPI automatically :tada: 

I'll take care of releasing 0.4.0 with the recent wave of fixes, and you can feel free to release any future versions as needed.  I'll still be around if I can be of any assistance, but I don't plan to do much active development.
