### ISSUE TITLE
Provide info about public IP and UPS status

### ISSUE THREAD

**Issue by EmAnzi3** [colinodell/python-qnapstats#46]
**Device Model Number**: `TS-653a`

**QTS Version**: `4.5.1.1540`

Beside thanking you for the useful tool you created I was wondering if there are chances to obtain some additional information from our QNAPs, in particular about:
- Public IP: I find very useful to check this information when I put the device under VPN via QVPN
- UPS Status: I personally have a CyberPower CP1500EPFCLCD protecting my NAS where I can see his status (battery capacity and estimated protection time)
I was just wondering if there is any chance to implement this information, thanks!

**Comment by colinodell** [comment]
Those are great ideas!  It should be possible to somehow obtain that information - it's just a matter of reverse-engineering the AJAX calls used by the web interface so we know where/how to get that.  I personally do not plan to implement those features, but if anyone else would like to then I would gladly accept those contributions!
