### ISSUE TITLE
Works with TS-210 and firmware 4.2.6

### ISSUE THREAD

**Issue by mihaur** [colinodell/python-qnapstats#47]
**Device Model Number**: TS-210

**QTS Version**: 4.2.6 (latest for the model)

It works from python CLI program and integrated into HA.
I get all metrics, except CPU temperature which is apparently not reported by T-210.

![ha-t210](https://user-images.githubusercontent.com/10325909/105610050-88284d00-5dad-11eb-8706-eca1194e9caf.PNG)

👏 Thanks for your work on this project!

**Comment by colinodell** [comment]
Awesome, thanks for letting me know! I've added TS-210 as a working model in the README :)
