### ISSUE TITLE
Additional model entry that I can confirm DOES work for your next revision of compatible systems

### ISSUE THREAD

**Issue by taw123** [colinodell/python-qnapstats#57]
**Device Model Number**:  TVS-872XT

**QTS Version**:  4.5.2.1630

Just a quick note for your next readme revision. qnapstats is working great on my TVS-872XT, surfacing data up through HomeAssistant.

I DID have a request in terms of feature enhancement and don't know if you want to keep the issues separate for tracking purposes, so let me know if you prefer me to file an additional (enhancement) issue independent of this Documentation issue.

The request is to surface if possible Thunderbolt Network performance (as you do with en0, en1, en2, etc). I was looking to see if I could get current & graphed data for tb1 and tb2. Not sure where to hook to but data is of course present in Q'center so HOPEFULLY it's also programmatically accessible to you if you were to offer to pass up any additional network bridges present. I would assume this might also include WiFi or USB bridges IF QNAP names them maps them appropriately for you to enumerate.

Thanks again for a great solution and only HOPE it can get better. Finally as a long time network engineer myself and developer if I can help test or provide insight/assistance, more than willing to help out for all.

All the best!
-Tom

**Comment by colinodell** [comment]
Hey Tom,

As mentioned in #43 I am no longer actively developing new features for this library, though I will gladly accept any PR (with sufficient tests) that implements this new feature!
