### ISSUE TITLE
TS-869 Pro and TS-853 Pro are compatible

### ISSUE THREAD

**Issue by workflowsguy** [colinodell/python-qnapstats#64]
**Device Model Number**: TS-869 Pro
**QTS Version**: 4.3.4.1652

**Device Model Number**: TS-853 Pro
**QTS Version**: 4.5.4.1741

When running the example script on the main page, I can confirm that these two models will return the complete  information.

Regards,
Guy

**Comment by colinodell** [comment]
Thanks so much! I've updated the README accordingly.
