### ISSUE TITLE
support fans speed in the furture?

### ISSUE THREAD

**Issue by cooshare** [colinodell/python-qnapstats#72]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: <TS-251D>

**QTS Version**: <5.0.0>

If you're reporting a `KeyError`, please also provide the XML response from your QNAP device.  You can easily obtain this by running the `debug.py` script.

**XML/Debug Output:**

~~~
<Insert your XML or debug output here>
~~~

**Comment by julien-bouquet** [comment]
Hello, 
If you have XML and if a i had time. I can try to integrate it

**Comment by pilot1981** [comment]
Hi, I can help? How I can extract XML from my QNAP to obtain fan speed?
