### ISSUE TITLE
CGI documentation

### ISSUE THREAD

**Issue by NachoParra** [colinodell/python-qnapstats#80]
Hi,

I have implemented this qnap stats as a web API to be called from an external system but I want to play a little bit more with the available CGIs to search for more stats that I can add to the project. I have searched for the Qnap CGI documentation but I can not find anywhere, without having registered myself as a developer on Qnap. Does anyone has this documentation available or do I have to register as a developer?

Regards,

Nacho

**Comment by mcclown** [comment]
I'm also interested in this documentation
