### ISSUE TITLE
QuTS 5.0.1.2376 and TS-873A not working from Home Assistant

### ISSUE THREAD

**Issue by digitalformula** [colinodell/python-qnapstats#84]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: TS-873a

**QTS Version**: QuTS h5.0.1.2376 (note QuTS, not QTS)

Details:

- TS-873A configured with non-standard SSL port
- QuTS user created without any restrictions
- QuTS user can login without issues
- All warnings and user-setup messages accepted as per integration docs
- Home Assistant 2023.7.1 says "Unknown error occurred" when configuring the QNAP integration
- Tested with SSL verification enabled and disabled.  Same result.
- Home Assistant logs indicate SSL cert verification should be enabled but don't contain any errors about connection

**Comment by VincenzoKoestler** [comment]
QuTS on 472XT works for me
