### ISSUE TITLE
TS-873A with QTS 5.0.1 is supported

### ISSUE THREAD

**Issue by DemianWright** [colinodell/python-qnapstats#86]
This device and firmware combination **is supported** (all sensors are working) through the Home Assistant integration, even though it is not listed in the support table. Although it seems like the QuTS Hero operating system is not supported when installed on this device as mentioned in issue #84.

**Device Model Number**: TS-873A
**QTS Version**: QTS 5.0.1.2248

I am using a custom SSL port, with SSL enabled but SSL verification disabled (enabling the verification leads to an error), and a custom user account.

**Comment by colinodell** [comment]
Thank you for this info! I've [updated the README](b97e0823410de43f9a47e1bc4d428231c5d12757) accordingly :)
