### ISSUE TITLE
Fix failing CI actions

### ISSUE THREAD

**Issue by colinodell** [colinodell/python-qnapstats#88]
Our CI tests are currently failing. They used to pass, so I'm guessing we might be relying on versions of something(s) that are too old and no longer supported? I'm not sure, but we should probably fix these so they pass once again.

**Comment by navdiya-nikunj** [comment]
Hello @colinodell  👋  can i work on this? I'll try to solve it.

**Comment by colinodell** [comment]
Sure!

**Comment by Anurag-Nagpal** [comment]
Hi @colinodell, I have made some changes to fix the CI actions, I see this issue has been assigned before while I was working on my changes. Let me know if you want to review and merge that PR #89

**Comment by colinodell** [comment]
Hi @Anurag-Nagpal, sure, I'll merge your MR :)

@navdiya-nikunj if you're still looking for something to do, maybe you could add newer versions of Python to the build matrix, and resolve any issues that come up?  Let me know if that's something you might be interested in (and no worries if not!)

**Comment by navdiya-nikunj** [comment]
I would love to do that. 

Actually I am new to open source so I just want to confirm that you want to test this project using python 3.10 and 3.11 and if any error occurs I have to resolve it right?

**Comment by colinodell** [comment]
Yes, exactly! And if you encounter any errors you can't fix, let us know and we will try to help :)
