### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by jamesgeddes** [colinodell/python-qnapstats#91]
**Device Model Number**: TS-453 Pro

**QTS Version**: 5.0.0.1932

I am currently seeing this in Home Assistant

![Screenshot from 2024-03-05 21-17-51](https://github.com/colinodell/python-qnapstats/assets/14872636/11f88a9f-f714-44bb-a1a0-2ffec57911c4)

Password is correct as it is copied and pasted from LastPass. The same credentials work when accessing storage.

Am I doing something wrong or is this a bug?

**Comment by colinodell** [comment]
It's hard to tell from this screenshot alone. Do you see any errors in the Home Assistant logs that seem relevant? We'd need to see those to troubleshoot this further.

**Comment by jamesgeddes** [comment]
Also getting this from the console;

```
CIFS: VFS: server [internal IP address] does not advertise interfaces
```

Does that help?

**Comment by jzucker2** [comment]
You're entering a DNS name. Have you tried getting the actual IP address of the NAS and using that instead?
