### ISSUE TITLE
delegate for monitoring system instead of full administrator account

### ISSUE THREAD

**Issue by rafalkalinski** [colinodell/python-qnapstats#95]
Please provide the following information along with your issue report (replace anything inside of `<>`):

**Device Model Number**: <TS-431XeU>

**QTS Version**: <5.1.7>

No error, but pls do not encourage users to turn off MFA for an administrator account. It's way safer to create a regular account and just delegate to that account an admin privilege for monitoring system.

**Comment by rafalkalinski** [comment]
One disadvantage: for some reason monitoring privilege doesn't give access for download and upload monitoring.

**Comment by hmonteiro** [comment]
Was just about to raise this issue as well. Delegation of the monitoring system should definitely be the recommended option with using an administrator account being presented as an option for people that want the few features that are not supported by the delegation and accompanied with the caveats about reduced security.
